version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the NGINX configuration file
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows Docker to connect to localhost
